[package]
name = "jmsrequest"
version = "0.1.0"
authors = ["sidhaler"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tokio-core = "0.1.18"
tokio = { version = "1", features = ["full"] }
